In [1]:
# import library
import numpy as np
import pandas as pd

In [2]:
# load data
data = pd.read_csv('dataset_sms_spam _v1.csv')

In [3]:
data.head()

Teks  label
0  [PROMO] Beli paket Flash mulai 1GB di MY TELKO...      2
1  2.5 GB/30 hari hanya Rp 35 Ribu Spesial buat A...      2
2  2016-07-08 11:47:11.Plg Yth, sisa kuota Flash ...      2
3  2016-08-07 11:29:47.Plg Yth, sisa kuota Flash ...      2
4  4.5GB/30 hari hanya Rp 55 Ribu Spesial buat an...      2

In [5]:
data.label.value_counts()

0    569
1    335
2    239
Name: label, dtype: int64

In [6]:
# mengubah data teks -> matriks
from sklearn.feature_extraction.text import CountVectorizer

vect = CountVectorizer()

vect.fit(data.Teks)

X = vect.transform(data.Teks)

In [9]:
# split train test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, data.label)

In [21]:
# train machine learning model
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import LinearSVC

model = MultinomialNB(alpha=0.8)

model.fit(X_train, y_train)

model2 = LinearSVC()

model2.fit(X_train, y_train)

LinearSVC(C=1.0, class_weight=None, dual=True, fit_intercept=True,
          intercept_scaling=1, loss='squared_hinge', max_iter=1000,
          multi_class='ovr', penalty='l2', random_state=None, tol=0.0001,
          verbose=0)

In [22]:
# lakukan prediksi
y_pred = model.predict(X_test)
y_pred2 = model2.predict(X_test)

In [23]:
# evaluasi model
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.metrics import classification_report
print("NAIVE BAYES")
print("confusion matrix : ")
print(confusion_matrix(y_pred, y_test))
print("Accuracy Score : ")
print(accuracy_score(y_pred, y_test))
print("classification report : ")
print(classification_report(y_pred,y_test))
print()
print("Linear SVM")
print("confusion matrix : ")
print(confusion_matrix(y_pred2, y_test))
print("Accuracy Score : ")
print(accuracy_score(y_pred2, y_test))
print("classification report : ")
print(classification_report(y_pred2,y_test))

NAIVE BAYES
confusion matrix : 
[[122   2   0]
 [  1  84   2]
 [  4   8  63]]
Accuracy Score : 
0.9405594405594405
classification report : 
              precision    recall  f1-score   support

           0       0.96      0.98      0.97       124
           1       0.89      0.97      0.93        87
           2       0.97      0.84      0.90        75

    accuracy                           0.94       286
   macro avg       0.94      0.93      0.93       286
weighted avg       0.94      0.94      0.94       286


Linear SVM
confusion matrix : 
[[126   1   1]
 [  1  89   3]
 [  0   4  61]]
Accuracy Score : 
0.965034965034965
classification report : 
              precision    recall  f1-score   support

           0       0.99      0.98      0.99       128
           1       0.95      0.96      0.95        93
           2       0.94      0.94      0.94        65

    accuracy                           0.97       286
   macro avg       0.96      0.96      0.96       286
weighted avg  

In [17]:
# masukkan data baru 
sms_baru = ["halo, apa kabar ? ",
            "pinjaman tanpa jaminan hanya disini",
            "promo paket flash 1 GB hanya Rp. 10000"
            ]

# langkah 1 : ubah dari teks -> matriks
sms_baru_vec = vect.transform(sms_baru)

# langkah 2 : masukkan kedalam model machine learning
hasil = model.predict(sms_baru_vec)

print(hasil)

[0 1 2]
